version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:16  # Version auf 16 gesetzt
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - postgres
    restart: unless-stopped
  stevecode-fullstack:
    container_name: stevecode-fullstack
    image: stevecodestuff/stevecode-fullstack
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
    command:
      - --spring.datasource.url=jdbc:postgresql://postgres:5432/customer



  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - db

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
